# fly.toml app configuration file generated for armi91-datingapp on 2023-11-23T00:22:05+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "armi91-datingapp"
primary_region = "waw"

[build]
  image = "armi91/datingapp"

[env]
  ASPNETCORE_URLS = "http://+8080"
  CloudinarySettings__CloudName = "dlp6ztotg"
  CloudinarySettings__ApiKey = "112387298217171"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
